### ISSUE TITLE
Infografia (Hilos)

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/infografia-de-hilos-abicoronel#3]
[Infografia (hilos) Abigail Coronel Santiago.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-abicoronel/files/8376732/Infografia.hilos.Abigail.Coronel.Santiago.pdf)

**Comment by SANDRAVELASCO** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
